MOSIP-28887
mosip/mosip-data pull request #254
Opened 2023-08-23 07:25 UTC by ase-101

2023-08-24 08:48 UTC, sowmya695 commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/upgrade.properties
> +UPGRADE_DOMAIN_NAME=api-internal.upgrade2.mosip.net
@ase-101 ,If this is hardcoded to upgrade2,then script will work only for this env .is it fine?

2023-09-06 09:39 UTC, balaji-alluru commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/upgrade.properties
> +UPGRADE_DOMAIN_NAME=api-internal.upgrade2.mosip.net
Before running these scripts devops team will update the properties accordingly ma'am, so it'll be fine.

2023-09-08 07:31 UTC, vishwa-vyom requested changes

2023-09-08 07:31 UTC, vishwa-vyom commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/migration-ui_spec.py
> +							}]
To check with Rounak, this configuration was hardcoded in 1.1.5.5 reg client, is it possible that countries would have customized this ?

2023-09-14 08:35 UTC, ase-101 commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/migration-ui_spec.py
> +							}]
yeah spoke with Rounak on this vishwanath, we will move this to properties file with default on how it was in 1.1.5.* reg-client. If a country has customized it they will have to update it here - this will be documented.

2023-09-22 07:08 UTC, sowmya695 approved these changes

2023-09-27 14:40 UTC, vishwa-vyom requested changes

2023-09-27 14:40 UTC, vishwa-vyom commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/migration-ui_spec.py
> +	print(guardian_bio_field)
Do we need the above print statements ?

2023-09-27 14:40 UTC, vishwa-vyom commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/migration-ui_spec.py
> +allBioAttributes = ["leftEye","rightEye","rightIndex","rightLittle","rightRing","rightMiddle","leftIndex","leftLittle","leftRing","leftMiddle","leftThumb","rightThumb","face"]
Can we take this from some properties file ?  Is it possible that countries might use a subset of these attributes ?

2023-10-09 15:29 UTC, ase-101 commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/migration-ui_spec.py
> +	print(guardian_bio_field)
removed unwanted prints

2023-10-09 15:29 UTC, ase-101 commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/migration-ui_spec.py
> +allBioAttributes = ["leftEye","rightEye","rightIndex","rightLittle","rightRing","rightMiddle","leftIndex","leftLittle","leftRing","leftMiddle","leftThumb","rightThumb","face"]
yes its moved to properties file

2023-10-10 05:11 UTC, vishwa-vyom requested changes

2023-10-10 05:11 UTC, vishwa-vyom commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/upgrade.properties
> +SECONDARY_LANGUAGE_CODE=ara
can't we keep this and other configs like dbuser empty ?

2023-10-10 06:15 UTC, ase-101 commented on mosip_master/data_upgrade/1.1.5.5_to_1.2.0.1/upgrade.properties
> +SECONDARY_LANGUAGE_CODE=ara
removed

2023-10-10 06:33 UTC, vishwa-vyom approved these changes

2023-10-10 06:33 UTC, merged