[MOSIP-29946] Added workflow to Test mosip-data.
mosip/mosip-data pull request #280
Opened 2023-12-15 04:22 UTC by VSIVAKALYAN

2023-12-15 13:11 UTC, syedsalman3753 requested changes
Add a step to check if postgres-init for mosip_master db completed sucessfully.

2023-12-19 06:44 UTC, VSIVAKALYAN commented
@syedsalman3753 added the step where it will Check for the Errors in container & exit with code1 if error exists & if not exit with code0 So please Check & approve PR.

2023-12-19 07:01 UTC, syedsalman3753 requested changes

2023-12-19 07:24 UTC, syedsalman3753 requested changes

2023-12-19 07:24 UTC, syedsalman3753 commented on .github/workflows/push-trigger.yml
> +        - 1.2.0.1
@VSIVAKALYAN 

syntax is not correct please update it

2023-12-19 07:35 UTC, syedsalman3753 approved these changes

2023-12-19 09:38 UTC, ckm007 commented on .github/workflows/push-trigger.yml
> +      - 1.2.0.1
add MOSIP* also to push branches.

2023-12-19 10:13 UTC, merged